### ISSUE TITLE
Input display enhancement

### ISSUE THREAD

**Issue by Dgc2002** [SerpentAI/Serpent#2]
Currently AIsaac's current input category(random/predicted) and inputs are displayed like this:  

![image](https://user-images.githubusercontent.com/3957791/27137028-681102e0-50e2-11e7-9882-9067bea38a64.png)
  
I'd like to suggest displaying this information in the visual debugger during runs, currently this is filled with the last set of flashbacks. I think a setup similar to input displays used by some speedrunners would be fitting. For these examples I used [NohBoard](https://sourceforge.net/projects/nohboard/) with the Isaac layout.  
  
Default:  
![aisaac default](https://user-images.githubusercontent.com/3957791/27137127-b9ec51aa-50e2-11e7-9dc3-d64a44e906b4.png)
  
Random:  
![aisaac random](https://user-images.githubusercontent.com/3957791/27137139-c17f779e-50e2-11e7-8f9e-e862950bfc90.png)
  
Predicted:  
![aisaac predicted](https://user-images.githubusercontent.com/3957791/27137145-c5768d06-50e2-11e7-9125-7148f8f8619f.png)

**Comment by nbrochu** [comment]
<img width="273" alt="screen shot 2017-06-19 at 5 02 09 am" src="https://user-images.githubusercontent.com/35039/27277903-d7c39138-54ad-11e7-9eaa-18a5fed33e68.png">

This overlay is now over the game and can easily be reconfigured for other games and/or input schemes.
